version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/opt/app/api
    ports:
      - 3000:3000
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    depends_on:
      - app